/**
 * Workflow Module Interfaces
 *
 * OWNED BY: Member 2 (Frontend & Integration Lead) & Member 5 (AI Workflow Planning)
 *
 * When ready to integrate React Flow:
 * 1. Install `@xyflow/react` (the modern React Flow package).
 * 2. Implement the visual canvas inside `src/modules/workflow/components/`.
 * 3. Support human-in-the-loop approval nodes and execution steps generated by the AI Copilot.
 */

export type WorkflowStepType =
  | "dataset_input"
  | "spatial_filter"
  | "buffer_geometry"
  | "overlay_analysis"
  | "ai_classification"
  | "human_approval_gate"
  | "export_results";

export type ExecutionState = "idle" | "running" | "paused_for_approval" | "completed" | "failed";

export interface WorkflowNode {
  id: string;
  type: WorkflowStepType;
  label: string;
  position: { x: number; y: number };
  status: ExecutionState;
  parameters?: Record<string, unknown>;
}

export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
}

export interface WorkflowGraph {
  id: string;
  title: string;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  state: ExecutionState;
}

export interface HumanApprovalGate {
  nodeId: string;
  stepName: string;
  estimatedCost?: string;
  dataSummary: string;
  isApproved: boolean;
}

export interface WorkflowComponentProps {
  workflow?: WorkflowGraph;
  onExecute?: (workflowId: string) => void;
  onApproveStep?: (nodeId: string) => void;
}
